name: Python package

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4  # 5.4.0 drops Python 3.8 support
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install testtools pbr ruff
    - name: Run ruff
      run: |
        python -m ruff check .
    - name: Run ruff format
      run: |
        python -m ruff format --check .
    - name: Test with testtools
      run: |
        python -m testtools.run testscenarios.tests.test_suite
